model_name: EIN
dataset: Twitter
num_classes: 2
language: en
word_embedding: word2vec
result_name: Twitter_NEGT_word2vec
experiment_mode: id
ood_source_datasets: []
ood_val_domain: source
debug: false
seed: 0
device: cuda
lr: 0.001
weight_decay: 0.01
patience: 10
n_epochs: 100
selection_metric: val_loss
split: '622'
num_workers: 0
base_model: NEGT
batch_size: 32
hidden_dim: 64
in_feats: 200
tokenize_mode: naive
k: 10000
vector_size: 200
undirected: false
dropout: 0.5
max_hop: 147
negt_hidden_dim: 128
negt_heads: 4
negt_dropout: 0.5
negt_info_loss_weight: 1.0
negt_init_r: 0.9
negt_final_r: 0.8
negt_decay_interval: 10
negt_decay_r: 0.1
negt_attention_scale: 1000.1
negt_concat: false
negt_use_gnn: false
