# model and data
model_name: EIN
dataset: Weibo
num_classes: 2
language: ch
word_embedding: word2vec
e5_model_name: intfloat/multilingual-e5-base
e5_max_length: 128
e5_batch_size: 64
result_name: kagnn_kagcn_directed_valloss_word2vec
experiment_mode: id
ood_source_datasets: []
ood_val_domain: source
debug: False

# training parameters
seed: 0
device: cuda
lr: 0.0005
weight_decay: 0.00001
patience: 10
n_epochs: 100
selection_metric: val_loss
split: '622'
num_workers: 0

# model parameters
base_model: KAGNN
batch_size: 128
hidden_dim: 128
in_feats: 200
tokenize_mode: jieba
k: 10000
vector_size: 200
undirected: False
dropout: 0.3
global_pool: mean
max_hop: 72
lamda: 0.0
classification_class_weights: [1.0, 1.0]

# KAGNN parameters
kagnn_variant: KAGCN
kagnn_num_layers: 2
kagnn_hidden_layers: 1
kagnn_grid_size: 4
kagnn_spline_order: 3
kagnn_heads: 4
